name: NET8 Branch Build

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - net8
    paths-ignore:
      - '.github/**'
      - '*.yml'
      - '*.json'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: '8.x.x'
      - name: Restore dependencies
        run: |
          dotnet restore
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/net8/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Build
        run: |
          dotnet build --no-restore --configuration Release
